language: node_js
node_js:
  - 0.10
  - 4
  - 6
  - 7
  - 8
  - 9
script:
  - npm run lint
  - npm run test
  - npm run test-coverage && cat coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf coverage
